services:
  postgres:
    image: postgres:14-alpine
    container_name: rolled-pg
    restart: always
    env_file: "dev.env"
    ports:
      - "5432:5432"
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rolled
  typesense:
    image: typesense/typesense:28.0
    container_name: rolled-ts
    restart: on-failure
    env_file: "dev.env"
    ports:
      - "8108:8108"
    volumes:
      - ./typesense_data:/data
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: true
  ingestion:
    build:
      context: ingestion/.
    container_name: rolled-ingestion
    restart: on-failure
    env_file: "dev.env"
    environment:
      ING_POSTGRES_HOST: rolled-pg
      ING_POSTGRES_PORT: 5432
      ING_POSTGRES_USERNAME: root
      ING_POSTGRES_DATABASE: rolled
      ING_TYPESENSE_HOST: typesense.apps.wuvt.vt.edu
      ING_TYPESENSE_PORT: 443
      ING_TYPESENSE_PROTO: https
    volumes:
      - ./ingestion_data:/data
  frontend:
    build:
      context: frontend/.
    container_name: rolled-fe
    restart: always
    env_file: "dev.env"
    ports: 
     - 1337:80
    environment:
      FE_TYPESENSE_HOST: localhost
      FE_TYPESENSE_PORT: 8108
      FE_TYPESENSE_PROTO: http
      FE_ALLOWED: "192.168.0.0/24 10.23.0.0/16 10.89.0.0/24 172.16.0.0/12 fd00::/8"