name: Build and push Docker images
on:
  push:
    tags:
      - 'frontend-*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get release version
      id: get_version
      run: echo RELEASE_VERSION=$(echo ${GITHUB_REF:20}) >> $GITHUB_ENV
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_BUILDKIT: "1"
      with:
        name: wuvt/rolled-frontend
        username: wuvt
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: frontend
        dockerfile: Dockerfile
        tags: "latest,${{ env.RELEASE_VERSION }}"
